mastodon/src/main/res/values/colors.xml

Fixes the PopUp color, by changing it to a Nord themed color
| Before                                                                                                           | After                                                                                                           |
|------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| ![Before](https://user-images.githubusercontent.com/63370021/209354060-5c9625eb-c150-46a8-ae51-b72e2dabd8dc.png) | ![After](https://user-images.githubusercontent.com/63370021/209354049-090bdcca-4970-4817-b4a4-478b45ad23cc.png) |

feat(theme/nord): change popup color

---

mastodon/src/main/res/color/bookmark_icon.xml
mastodon/src/main/res/color/favorite_icon.xml
mastodon/src/main/res/values/attrs.xml
mastodon/src/main/res/values/colors.xml
mastodon/src/main/res/values/palettes.xml

Changes the selected favorite and bookmark icon color to be depended on the current theme. This is only implemented in this pr for the nord theme, but can be also done for the other themes (e.g. Material you would be a prime candidate).
I think it is worthwhile implementing this now, as it can be used for future themes with custom colors.
| Before                                                                                                           | After                                                                                                           |
|------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------- …

feat(theme/nord): add favourite and bookmark icon

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ComposeFragment.java
mastodon/src/main/res/values/strings_sk.xml

Adds a warning dialog when publicly posting images that have no description. The user still has the choice to publish anyway, or to chancel. 
Some instance, [for example floss.social](https://floss.social/@admin/109451240614809749), already require all public post to include image descriptions.

feat(compose/publish): Add warning dialog when no image description is provided

---

mastodon/src/main/res/layout/display_item_footer.xml

Adds `toolTipText` to the `reply`, `favourite` and `bookmark` icon button. The `share` and `boost` buttons both have additional functionality when long pressing, so it's not possible to show a tooltip on them.

feat(status/footer): add tooltips to icons

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ProfileFragment.java
mastodon/src/main/res/menu/profile_own.xml

This moves some of the icons into an overflow menu. This is necessary, as currently up to six icons will be displayed (according to the [Material Guidelines](https://m3.material.io/components/top-app-bar/guidelines#b1b64842-7d88-4c3f-8ffb-4183fe648c9e) only three should be displayed and less important ones moved to an overflow menu), causing layout issues, as can be seen in the Before example screenshot. The layout problem is worsened on smaller phones and for users with longer names. 
The moved options are rarely used, or in the case of the `Followed Hashtags` options even redundant, as the same functionality is provided by the new timeline layout. 
| Before                                                                                                           | After …

feat(profile): move options to overflow menu

---

mastodon/src/main/res/layout/fragment_compose.xml

Fixes an issue with the margin in the compose UI by removing it. Notice how the small gray strip (it's more noticeable on a device) is gone.
| Before                                                                                                           	| After                                                                                                           	|
|------------------------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------------------	|
| ![Before](https://user-images.githubusercontent.com/63370021/216839159-2b0ee57e-8dc1-49f0-8db2-dfbbfd84ca6c.png) 	| ![After](https://user-images.githubusercontent.com/63370021/216839150-4d7e4 …

fix(compose): remove marginEnd

---

mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/FooterStatusDisplayItem.java
mastodon/src/main/res/layout/display_item_footer.xml

Fixes and re-enables the star animation, which was broken by https://github.com/LucasGGamerM/moshidon/commit/31d0bfb43423de98770bea936ed65856d123626e and disabled in https://github.com/LucasGGamerM/moshidon/commit/2b7f3253325c1379ec97b071530d9ea26c0eb39c. Please notice that I have no idea what the result of changed code was, so it's quite possible, that it broke something else, which I didn't notice.

fix(star-animation): re-enable star animation

---

mastodon/src/main/java/org/joinmastodon/android/fragments/EditTimelinesFragment.java

By default, the Timeline URL input field show the text of the publish button, which this pr removes-
| Before                                                                                                           	| After                                                                                                           	|
|------------------------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------------------	|
| ![Before](https://user-images.githubusercontent.com/63370021/220170311-6e4515c0-86db-46d0-8523-53af2d45b481.png) 	| ![After](https://user-images.githubusercontent.com/63370021/220170301-e09ffa1b-44f4-4eef-af35-cab61b3df49b.png) 	|

fix(custom-timelines): remove default text

---

mastodon/src/main/java/org/joinmastodon/android/fragments/EditTimelinesFragment.java

Sets the `InputType` of the custom timeline URL edittext to `TYPE_TEXT_VARIATION_URI`, which makes it easier to enter URLs, by adding dedicated keys for top level domains and turning off some parts of AutoCorrect, like auto-placing a space after a dot.

feat(custom-timelines): use URI InputType

---

mastodon/src/main/java/org/joinmastodon/android/MainActivity.java
mastodon/src/main/java/org/joinmastodon/android/PushNotificationReceiver.java
mastodon/src/main/java/org/joinmastodon/android/model/NotificationAction.java
mastodon/src/main/res/values/strings_sk.xml

Adds actions to some notifications. Current supported notifications are `UPDATE`, `MENTION` and  `STATUS`. For `MENTION` and  `STATUS` are actions to Favorite, Bookmark and Boost (only shown if the post can be boosted, uses the account's default visibility for boosting) shown.  Each action can only be clicked once, after which the notification disappears. 
For `UPDATE` notifications, an action to unboost the post is added.
For the other notifications, `reblog`, `follow`, `favourite`, `poll` are items, which are not actionable (there is nothing the user can do about them, except see them, which should rather be to tap the notification), and I'm too inexperienced with the two admin related ones. From the app is the type for `follow_request` missing, which could have the actions `Accept` and …

Feat: Add actions to notifications

---

mastodon/src/main/java/org/joinmastodon/android/GlobalUserPreferences.java
mastodon/src/main/java/org/joinmastodon/android/PushNotificationReceiver.java
mastodon/src/main/java/org/joinmastodon/android/fragments/HomeFragment.java
mastodon/src/main/res/drawable/ic_notifications_tab_badged.xml

Adds a badge to the notification tab icon, if the user has unread notifications. It disappears, when the notifications tab is opened. The badge will not get added, if the app is currently open and a new notification arrives, only if it's closed.

Feat(tabs): add unread badge to notification tab

---

mastodon/src/main/java/org/joinmastodon/android/PushNotificationReceiver.java
mastodon/src/main/java/org/joinmastodon/android/model/NotificationAction.java
mastodon/src/main/res/values/strings_sk.xml

Adds a reply action to the `status` and `mention` notifications.
The user then has the option to directly reply, the reply will use the user's default posting language and status visibility, if the status had a spoiler warning, the reply will have the same spoiler text prepended with `re:`, similar to how it works in the compose screen.
After replying, the notification will get replaced by a new one, stating `Successfully replied to the post by [account name]`, although it didn't work for me reliably.

feat(notification): add reply action

---

mastodon/src/main/java/org/joinmastodon/android/api/requests/accounts/SetAccountMuted.java
mastodon/src/main/java/org/joinmastodon/android/ui/utils/UiUtils.java
mastodon/src/main/res/layout/item_mute_duration.xml
mastodon/src/main/res/menu/mute_duration.xml
mastodon/src/main/res/values/strings_mo.xml

Adds a user selectable mute timer to the mute confirmation dialog. The options are the same as on the web UI.
The dialog will not show the duration picker when unmuting someone.
I'm aware, that the current design is not optimal, however, so is my ability to improve it, so I will just leave it like it is for now.

feat: add mute timer

---

mastodon/src/main/java/org/joinmastodon/android/fragments/EditTimelinesFragment.java
mastodon/src/main/res/layout/header_welcome_custom.xml

Fixes an issue with the implementation from #96 and #100, both were not correctly applied on all phones, and would still show the wrong input type.

fix: apply URI InputType correctly

---

mastodon/src/main/java/org/joinmastodon/android/fragments/CustomLocalTimelineFragment.java
mastodon/src/main/java/org/joinmastodon/android/ui/text/HtmlParser.java

Closes #107. Instead of using the (wrong) profileID on CustomTimelines, use the URL, which will be correctly resolved.
https://user-images.githubusercontent.com/63370021/225416672-d3b50d9e-9a9a-422b-8db1-d33c6e9fafdc.mp4

fix(custom-timelines): lookup profile by url

---

mastodon/src/main/java/org/joinmastodon/android/DomainManager.java
mastodon/src/main/java/org/joinmastodon/android/MainActivity.java
mastodon/src/main/java/org/joinmastodon/android/fragments/BaseStatusListFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/CustomLocalTimelineFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/DomainDisplay.java
mastodon/src/main/java/org/joinmastodon/android/fragments/HashtagTimelineFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/HomeFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/HomeTabFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/HomeTimelineFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/NotificationsFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/NotificationsListFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/PinnableStatusListFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/ProfileFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/StatusListFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/ThreadFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverAccountsFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverNewsFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverPostsFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/FederatedTimelineFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/LocalTimelineFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/SearchFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/TrendingHashtagsFragment.java

Closes #119 by using the Pixel exclusive URL feature in the recent screen. It shows the web domain of the content that is displayed, for example, in the profile view the URL of the profile is shown, in a timeline, the timeline URL, etc…. Custom timelines will only show the default URL, without the added path for the local timeline.
This is a bit of a hacky solution, as the app only has one actual activity, but many different fragments with different URLs.

Feat:  Add recents URL sharing (Pixel exclusive)

---

mastodon/src/main/AndroidManifest.xml
mastodon/src/main/java/org/joinmastodon/android/ExternalShareActivity.java
mastodon/src/main/java/org/joinmastodon/android/fragments/HomeFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/ProfileFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/onboarding/AccountActivationFragment.java
mastodon/src/main/java/org/joinmastodon/android/ui/AccountSwitcherSheet.java
mastodon/src/main/res/layout/item_account_switcher.xml
mastodon/src/main/res/values/styles.xml

Closes #67. Removes the old share dialog and replaces it with a new transparent AccountSwitcherSheet. The AccountSwitcherSheet is refactored to be able to be used both for choosing and switching accounts.
Please note, that this UI design is not final has and has to still be polished before the next release.

Feat: redesign external share sheet

---

mastodon/src/main/java/org/joinmastodon/android/fragments/BaseStatusListFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/EditTimelinesFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/FollowRequestsListFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/FollowedHashtagsFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/HomeTabFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/ListTimelinesFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/NotificationsFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/ProfileFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/ScrollableToTop.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverAccountsFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverNewsFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/TrendingHashtagsFragment.java

Adds a double/triple click action to the tabs. When clicking the HomeTab a second time, and it's already scrolled to the top, it will cycle through the available timelines. The same feature is available on the notification tab.
https://user-images.githubusercontent.com/63370021/226114677-d15b5d61-4d02-4cba-be4d-b85c114bbf5f.mp4

Feat: Add tab triple click action

---

mastodon/src/main/java/org/joinmastodon/android/ExternalShareActivity.java
mastodon/src/main/java/org/joinmastodon/android/fragments/HomeFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/onboarding/AccountActivationFragment.java
mastodon/src/main/java/org/joinmastodon/android/ui/AccountSwitcherSheet.java
mastodon/src/main/res/layout/item_account_switcher.xml
mastodon/src/main/res/values/strings_mo.xml

Adds the options to the share menu to open a mastodon URL inside the app, instead of sharing it. This is a band-aid fix to https://github.com/sk22/megalodon/issues/450, as it does not actually solve the issue, just merely providing a work-around.
The option to open the URL will only be shown, if the shared text could be a mastodon link, otherwise the previous only the normal share sheet is shown.

Feat: share URL to open

---

mastodon/src/main/java/org/joinmastodon/android/fragments/HomeTabFragment.java

Fixes an issue, where tapping the home tab would cycle instead of showing new posts.

fix(home-double-tab): scroll up for new posts

---

mastodon/src/main/java/org/joinmastodon/android/fragments/HomeTabFragment.java

Fixes an issue, where clicking on the show new posts button would switch timelines instead of scrolling up.

fix(hometimeline): scroll up on tapping new post button

---

mastodon/src/main/java/org/joinmastodon/android/fragments/SettingsFragment.java

Shows the instance settings URL in the settings page.

fix(recent-url): show settings URL

---

mastodon/src/main/java/org/joinmastodon/android/GlobalUserPreferences.java
mastodon/src/main/java/org/joinmastodon/android/PushNotificationReceiver.java

Closes #129, by saving the last notification ID, as discussed in the issue. Even tough, only $2^{31}-1$ can potentially now be received before the counter would roll over, I don't consider this probable. If a user achieves it, prompting them to clear the data/reinstall the app is a viable solution.
Please note, that this code was not verified to actually fix the issue, as it's incredibly hard to reproduce, but it should likely fix it.

fix(notification): overwriting IDs

---

mastodon/build.gradle
mastodon/src/main/AndroidManifest.xml
mastodon/src/main/java/org/joinmastodon/android/api/session/AccountSessionManager.java

Changes the `REDIRECT_URI` to depend on the `BuildType`. This results in the removal of the app-choose-dialog, which fixes an issue, where the callback would not correctly work when choosing the app.
The GitHub and Play variant still use the old callback, only the debug and nightly Build Types get new callbacks, `moshidon-android-debug-auth` and `moshidon-android-nightly-auth` respectively.

fix: use BuilType defined REDIRECT_URI

---

mastodon/src/main/java/org/joinmastodon/android/fragments/account_list/BaseAccountListFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/account_list/PaginatedAccountListFragment.java

Refactor the remote follower code, removing duplication and making it easier to read.
Also fixes a few minor things, like accounts on the home instance not loading, and sets the display of home instance accounts correctly, back to what is was before.

Refactor remote follower

---

mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/ExtendedFooterStatusDisplayItem.java

Hides the number of boosts on `DIRECT` statuses, as they cannot be boosted.

feat(status): hide boosts on direct privacy

---

mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/TextStatusDisplayItem.java

Fixes an issue, where the translation would fail for custom timelines. Although the status is reloaded with the correct ID, it is not actually used when loading the translation.
I also took this opportunity to refactor the duplicated code into its own function.

fix(translation): use lookUp status id for request

---

mastodon/src/main/java/org/joinmastodon/android/ui/utils/UiUtils.java
mastodon/src/main/res/values/strings_mo.xml

Shows a dialog to confirm unfollowing a user. This option is also available on the web client. It is the new default behavior, as it is easier to accidentally click the button on a mobile device than on the web.
I also refactored the  `performAccountAction` method to remove duplicated code.

Feat: show unfollow confirmation dialog

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ThreadFragment.java
mastodon/src/main/java/org/joinmastodon/android/model/Status.java
mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/ExtendedFooterStatusDisplayItem.java
mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/FooterStatusDisplayItem.java

A follow-up to https://github.com/LucasGGamerM/moshidon/pull/174, hiding the `reblogCount` on _all_ private statuses, and not just private ones. As this check is identical to the one for the boost action itself, it has been moved to the status class.

feat: hide reblogs count on non-rebloggable status

---

mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/WarningFilteredStatusDisplayItem.java

Allows filter warnings to be revealed by clicking anywhere on the warning and not just by clicking on the button.

feat: reveal filter warning on click

---

mastodon/src/main/java/org/joinmastodon/android/fragments/InstanceInfoFragment.java

This hides the menu until then instance is loaded. This is done, so it is no longer possible to visit pages in the menu, as they relied on the instance being loaded and will crash the app otherwise.

fix(instance-info): hide menu until loaded

---

mastodon/src/main/java/org/joinmastodon/android/GlobalUserPreferences.java
mastodon/src/main/java/org/joinmastodon/android/fragments/settings/BehaviourFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsBaseFragment.java
mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/FooterStatusDisplayItem.java

Adds backwards compatibility for the new haptics feature from #214. Since this is an area of the Android API that has changed quite a lot recently, the appropriate API is used at each level. All API levels should be supported by it now.

feat: Add haptics compatibility for APIs 23-29

---

mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsAboutAppFragment.java

Allows the version name to be shown over multiple lines, as it can be quite long, especially for nightly builds.
| Before                                                                                                                             	| After                                                                                                                         	|
|------------------------------------------------------------------------------------------------------------------------------------	|-------------------------------------------------------------------------------------------------------------------------------	|
| ![Version name over multiple lines](https://github.com/LucasGGamerM/moshidon/assets/63370021/2956e76e-f4be-4368-8fbd-b5019af0840d) 	| ![Version name on …

fix: allow long version names

---

mastodon/src/main/res/color/favorite_icon.xml
mastodon/src/main/res/values/attrs.xml
mastodon/src/main/res/values/colors.xml
mastodon/src/main/res/values/palettes.xml

Minor fixes to the Nord theme. It still needs further fixes (menus have the wrong tint, compose hint looks like text), but at least the rest is more recognizable now.
Additionally, removes the `favorite_selected` color, as it has been replaced upstream by `colorFavorite`.

fix: small nord theme improvements

---

mastodon/src/main/java/org/joinmastodon/android/GlobalUserPreferences.java
mastodon/src/main/java/org/joinmastodon/android/fragments/HomeFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverNewsFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/TrendingHashtagsFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsDisplayFragment.java
mastodon/src/main/res/values/strings_mo.xml

Extends the functionality of https://github.com/LucasGGamerM/moshidon/pull/124.
Adds a new option to enable/disable the doubleTapToSearch behavior.
If it is disabled, allow for double tapping the Discover tab, to cycle through the Discover tabs.
Also changes the upstream longTap to open search to always open the search, regardless of what tab is currently selected.

feat: allow doubleTapToSwipe when doubleTapToSearch is disabled

---

mastodon/src/main/java/org/joinmastodon/android/fragments/HashtagTimelineFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/settings/EditFilterFragment.java
mastodon/src/main/res/menu/hashtag_timeline.xml
mastodon/src/main/res/values/strings_mo.xml

Closes https://github.com/LucasGGamerM/moshidon/issues/260 by adding the option to mute (create a filter) the hashtag.
This is marked as a draft because there are still some open questions, namely how the UI should handle hashtags that are already muted:
- Do nothing 
- Hide the mute option
- Show an unmute option
In the last two cases, the app has to query and iterate through the filters, as there is no native API to check if a hashtag is muted.
https://github.com/LucasGGamerM/moshidon/assets/63370021/e645f61f-657e-42b8-b82e-3b36d9ebd228

feat: add option to mute hashtag

---

mastodon/src/main/java/org/joinmastodon/android/fragments/BaseStatusListFragment.java

The old separators were too bright and distracted from text in the posts. So I made them look like separators in settings and profile pages.

Posts divider brightness fix (now looks like in settings and profile)

---

.github/workflows/nightly-builds.yml
mastodon/src/main/res/layout/tab_bar.xml

This changes the badge text to white and makes the nightly build available to manually run. This is untested.

Change badge color and add manual workflow

---

mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/NotificationHeaderStatusDisplayItem.java

Fixes a regression in 7b4be83781259ad8edf0c05eb6b304aa175201a2, by allowing to click on the entire item view, not just the avatar. This is helpful for accessibility and prevents accidental mis-clicks, and the avatar is a small touch target. The previous behavior of opening the post is maintained when clicking on the postcard below.

fix(notification): allow clicking on status item to open profile

---

mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsBehaviorFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsPrivacyFragment.java

Moves the "Reply as 'Unlisted' by default" setting to the privacy settings page. It fits better on the page since it affects how visible user replies are, similar to the default posting visibility. It also makes sense to keep it on the same page since both settings have a similar effect.

feat(settings): move unlisted replies to privacy page

---

mastodon/src/main/java/org/joinmastodon/android/fragments/NotificationsFragment.java
mastodon/src/main/res/values/strings_mo.xml

Renames the `Clear` button of the notification filter dialog to `Reset to default` to be more in line with how Android apps usually handle this. It also makes it easier to understand.
I also cleaned up the code for saving the preferences a bit.

fix(notification/filter) rename reset button

---

mastodon/src/main/java/org/joinmastodon/android/fragments/account_list/PaginatedAccountListFragment.java

Fixes a regression introduced  in 76867a971b5ff23e05e823620ce2d3ac5ccaa4f7, that caused remote info to be permanently disabled

fix(remote-info): remove null check

---

mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/FooterStatusDisplayItem.java

Fixes an issue, where the new reply sheet was only shown when using the new reply bar, and not the previous reply button, a regression, compared to upstream. Also slightly refactors the code to get rid of some duplicated code.

feat: show reply sheet on reply button

---

mastodon/src/main/res/layout/display_item_extended_footer.xml

Improves the extended footer, but re-adding the old background color and the icons.
| Before                                                                                                            	| After                                                                                                             	|
|-------------------------------------------------------------------------------------------------------------------	|-------------------------------------------------------------------------------------------------------------------	|
| ![Previous footer](https://github.com/LucasGGamerM/moshidon/assets/63370021/b56c59d0-14d7-460a-a70a-160a18a34fc5) 	| ![Improved footer](https://github.com/LucasGGamerM/moshidon/assets/63370021/44b4d605-9c2d-4695-803d-9dbaa8443edb) 	|

feat: improve extended footer

---

mastodon/src/main/java/org/joinmastodon/android/fragments/onboarding/SignupFragment.java
mastodon/src/main/java/org/joinmastodon/android/ui/sheets/DecentralizationExplainerSheet.java
mastodon/src/main/java/org/joinmastodon/android/ui/text/HtmlParser.java
mastodon/src/main/java/org/joinmastodon/android/ui/text/LinkSpan.java

Fixes a regression introduced in 0af8dbf09b7ca78f64842de479fdcb70ef6b86ac, taht caused the app to crash when long pressing on a hastag to copy it

fix: use correct hashtag text to prevent crash

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ProfileFragment.java
mastodon/src/main/java/org/joinmastodon/android/ui/sheets/DecentralizationExplainerSheet.java
mastodon/src/main/res/layout/sheet_decentralization_info.xml
mastodon/src/main/res/values/strings_mo.xml

Adds a `View Server Info` button to the new `DecentralizationExplainerSheet`, which opens the about page of the instance. This replaces the old behavior of the DecentralizationExplainerSheet only appearing on long press, which is pretty hard to discover.

feat: add instance info button to DecentralizationExplainerSheet

---

mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/ReblogOrReplyLineStatusDisplayItem.java

Fixes an issue, where the inline avatar was not displayed for boosted replies. I used to opportunity to also refactor the code a bit, removing some duplicated code and making it hopefully more readable.

fix: display inline avatar for boosted replies

---

mastodon/src/main/res/layout/fragment_profile.xml

| Before                                                                                                                                           	| After                                                                                                                                        	|
|--------------------------------------------------------------------------------------------------------------------------------------------------	|----------------------------------------------------------------------------------------------------------------------------------------------	|
| ![Bot icon displayed after the user display name](https://github.com/LucasGGamerM/moshidon/assets/63370021/f18e34b2-ecf1-45e7-9efe-7b73fdd7488f) 	| ![Bot icon displayed after the server …

fix(profile): display username icons after server

---

mastodon/src/main/java/org/joinmastodon/android/fragments/HomeFragment.java

Removes the `OnboardingFollowSuggestionsFragment` from showing when long pressing the home tab. This feature has been removed by upstream for a while now, and is already duplicated in the discovery tab, so there is no reason to keep it.

feat: remove home tab longpress

---

mastodon/src/main/java/org/joinmastodon/android/ui/text/LinkSpan.java

Fixes an issue where the link of a `LinkSpan` would not open in the browser because the wrong method was used. This could happen for example when clicking on a link in the profile fields.
*This should not have happened in Rust :crab: comment

fix: use correct openURL function

---

mastodon/src/main/java/org/joinmastodon/android/api/requests/accounts/SetAccountMuted.java
mastodon/src/main/java/org/joinmastodon/android/ui/sheets/AccountRestrictionConfirmationSheet.java
mastodon/src/main/java/org/joinmastodon/android/ui/sheets/MuteAccountConfirmationSheet.java
mastodon/src/main/java/org/joinmastodon/android/ui/utils/UiUtils.java
mastodon/src/main/res/values/strings_mo.xml

Re-adds the mute duration option to the new MuteConfirmationSheet.
Also adds the option to mute notifications from https://github.com/sk22/megalodon/pull/968.

feat: add mute duration and notifications to mute confirmation sheet

---

mastodon/src/main/java/org/joinmastodon/android/fragments/BaseStatusListFragment.java

Hopefully fixes the issue where the wrong StatusDisplayItem was removed when displaying a filtered item. This implementation is loosely based on [upstream](https://github.com/mastodon/mastodon-android/blob/36f4770cae58841b0da9364bf3d3bae853243782/mastodon/src/main/java/org/joinmastodon/android/fragments/BaseStatusListFragment.java#L434)'s.

fix: replace correct filter item

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ComposeFragment.java

Disables the group divider in the compose screen. See https://github.com/sk22/megalodon/pull/453 for more context.

fix(compose): disable group divider on EMUI

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ListsFragment.java

Fixes a regression in 0af8dbf09b7ca78f64842de479fdcb70ef6b86ac, where lists memberships where not saved, as the requests where not send to the server.

fix(lists): send requests for list membership

---

mastodon/src/main/java/org/joinmastodon/android/fragments/StatusEditHistoryFragment.java

Sometimes the server sends only the latest status instead of the full history. Try to avoid this by requesting the history directly from the server.
This may need further testing on nightly. [Example post for testing purposes.](https://livellosegreto.it/@gisk/112348457888576371)
| Before                                                                                                                                          	| After                                                                                                                                        	|
|-------------------------------------------------------------------------------------------------------------------------------------------------	|------------------------------------------------------------------------------- …

feat(StatusEditHistory): load remote history

---

mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsServerAboutFragment.java

The About screen often contains links the local accounts (e.g. moderators, admins) instead of always opening them in the browser, try to open them in-app first.

feat(about): try to open links in-app

---

mastodon/src/main/java/org/joinmastodon/android/fragments/EditTimelinesFragment.java

Fixes an issue, where Hashtag timeline were created with an empty hashtag. This would only apply when creating a fresh timeline for a hashtag that the user does not already follow.

fix: fallback to hashtag name

---

mastodon/src/main/java/org/joinmastodon/android/fragments/CustomLocalTimelineFragment.java

Fixes an issue, where the domain for the recents URL feature was incorrectly, without a scheme, displayed in CustomLocalTimelines.

fix(CustomLocalTimeline): set WebUri with scheme

---

mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverNewsFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/TrendingHashtagsFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/settings/BaseSettingsFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/settings/EditFilterFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsFiltersFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsNotificationsFragment.java

Prompted by https://github.com/LucasGGamerM/moshidon/pull/404, I've noticed a few more fragments that lost their implementation. I also re-implemented the URL for settings, since the upstream implementation did not have it. When possible, the equivalent web URL is displayed, otherwise just the generic `/settings` one.

feat: display URL in recents for more fragments

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ThreadFragment.java

Fixes an issue, where the wrong account could be passed to the ComposeView, when longpressing the replyBar and choosing an account.

fix(ThreadFragment): pass correct account to ComposeView

---

mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsNotificationsFragment.java
mastodon/src/main/res/values/strings_mo.xml

Displays a warning in the notifications settings fragment, if UnifiedPush is disabled (or cannot be enabled). The warning will be only displayed on the FDroid build variant, since other versions use FCM by default.
Should help a bit to avoid issues such as https://github.com/LucasGGamerM/moshidon/issues/341 and https://github.com/LucasGGamerM/moshidon/issues/337

feat: warn if UP is disabled on FDroid variant

---

mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/PollOptionStatusDisplayItem.java

Updates the animation timing, to be based on the amount of votes a option received relative to the other options. This means a option with more votes will run longer than one with less votes. Overall this makes the animation appear more dynamic and smoother.
Animation with equal duration:
[Poll animation with equal duration](https://github.com/LucasGGamerM/moshidon/assets/63370021/d19f6966-c541-4857-8961-50b79f684e21)
Animation with dynamic duration:
[Poll animation with dynamic duration](https://github.com/LucasGGamerM/moshidon/assets/63370021/cf1ed086-6531-42d1-a040-833f1ffcc5f9)

feat(Poll): scale animation based on votes

---

mastodon/src/main/java/org/joinmastodon/android/ui/photoviewer/PhotoViewer.java

Cleanup the code for sharing an image a bit, as well as showing a preview for the shared images, for devices running higher than API 29.

refactor: share img/show preview

---

mastodon/src/main/java/org/joinmastodon/android/ui/photoviewer/PhotoViewer.java

Refactors the share method of `PhotoViewer` to use the `UiUtils.getFileProviderUri` instead of its own implementation.

refactor(PhotoViewer): use getFileProviderUri

---

mastodon/src/main/java/org/joinmastodon/android/GlobalUserPreferences.java
mastodon/src/main/java/org/joinmastodon/android/fragments/report/ReportCommentFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsBehaviorFragment.java
mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/FooterStatusDisplayItem.java

Cleans up the settings by removing some of the more unnecessary settings:
- `hapticFeedback`: This can already be controlled from the Android settings
- `loadRemoteAccountFollowers`: this setting isn't used anywhere
- `forwardReportDefault`: I don't think there is any good reason to change the default value of the switch

feat: cleanup settings

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ThreadFragment.java

this will also expand content warnings that start with any variation like capitalized "RE:"

fix: make autoexpand content warning option also expand cws that start with "re:"

---

mastodon/src/main/java/org/joinmastodon/android/GlobalUserPreferences.java
mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsBehaviorFragment.java
mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/FooterStatusDisplayItem.java

Some OEMs do not implement a systemwide setting for touch feedback on older Android versions.
This reverts commit e0a793e17625e80f3f5be721dd38eb97db58a940.

revert: readd haptic feedback setting on Android 11 and lower

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ComposeFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/HomeTabFragment.java
mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/HeaderStatusDisplayItem.java
mastodon/src/main/java/org/joinmastodon/android/ui/utils/UiUtils.java
mastodon/src/main/java/org/joinmastodon/android/ui/viewholders/AccountViewHolder.java

They have the same invisibility bug as EMUI.
[Example](https://vmst.io/@maikel/112583425285066680)

fix: disable GroupDivider on Honor's MagicOS

---

mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/ErrorStatusDisplayItem.java

Fixes an issue in https://github.com/LucasGGamerM/moshidon/pull/426, where the app would crash, if the URL was null. To prevent that, the Open in Browser is disabled if the URL is null. This should however only be rarely the case.

fix(ErrorStatusDisplayItem): disable open in browser button on null URL

---

mastodon/src/main/java/org/joinmastodon/android/ui/sheets/AccountSwitcherSheet.java

Changes the AccountSwitcherSheet from always restarting the application to only restarting if a different account is selected. This reduces the friction of accidentally clicking on the same account.

fix(AccountSwitcherSheet): only restart on different accounts

---

mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/StatusDisplayItem.java

Hopefully fixes an issue, where the app could not [display scheduled statuses](https://mastodon.social/@iThreepwood/112597310727750819). Unfortunately I'm not able to reproduce this error on my emulator, so I wasn't able to test it.

fix(StatusDisplayItem): explictly copy filter list

---

mastodon/src/main/java/org/joinmastodon/android/api/requests/timelines/GetTrendingLinksTimeline.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverNewsFragment.java
mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverTrendingLinkTimelineFragment.java
mastodon/src/main/res/drawable/ic_fluent_document_one_page_24_filled.xml
mastodon/src/main/res/layout/header_trending_link_timeline.xml
mastodon/src/main/res/menu/trending_links_timeline.xml
mastodon/src/main/res/values/strings_mo.xml

For the upcoming v4.3 release, adds a timeline of statuses that posted about a trending link. See https://github.com/mastodon/mastodon/pull/30381 for more details.
Once v4.3 is fully released, the version check should be removed, as it will otherwise fail on newer relases.

feat(Discover): add Timeline to trending links

---

mastodon/src/main/java/org/joinmastodon/android/api/MastodonAPIController.java

Although a request is checked for a blocked domain, it is not actually blocked.

fix: block domains in block list

---

mastodon/src/main/java/org/joinmastodon/android/ui/text/HtmlParser.java

Some fediverse servers (e.g. lemmy) add a trailing line break to the content. Since we add them as well, this can cause up to three line breaks at the end of a post, resulting in a blank space. This removes the trailing line breaks before parsing the content.
| Before                                                                                                                                       	| After                                                                                                                      	|
|----------------------------------------------------------------------------------------------------------------------------------------------	|--------------------------------------------------------------------------------------------------------------------------- …

fix(HtmlParser): remove trailing line breaks

---

mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/ErrorStatusDisplayItem.java

Fixes a NullPointerException, where the `item` was null in the constructor, ironically causing the ErrorStatusDisplayItem to crash immediately.

fix(ErrorStatusDisplayItem): disable button in onBind

---

mastodon/src/main/java/org/joinmastodon/android/fragments/BaseStatusListFragment.java
mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/StatusDisplayItem.java

Improves the non-official quote posts by:
- compiling the regex outside the function, improving performance
- using the regex to find the last URL
- rebuilding the entire Status, avoiding separate code paths
- not showing self-referential quotes, causing an infinite loop (and requests)
- hiding the URL used to construct the quote, with an optional "RE:" prefix

feat: improve non-official quote posts

---

mastodon/src/main/java/org/joinmastodon/android/fragments/BaseStatusListFragment.java

Likely fixes an `java.lang.IndexOutOfBoundsException` crash introduced in https://github.com/LucasGGamerM/moshidon/commit/38df70cd9ecbacbd55f53ac0f6d1d3f0eea1d5db.

fix(StatusDisplayItem): check if headerlist is empty

---

mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/StatusDisplayItem.java

Some instance use a closing line break instead of a normal one.

fix(StatusDisplayItem): allow closing linebreak tag in quote regex

---

mastodon/src/main/AndroidManifest.xml
mastodon/src/main/java/org/joinmastodon/android/ui/utils/UiUtils.java

Shows the profile picture of the shared account in the share sheet. This was already done upstream and intended here, but was bugged due to an additional file provider.

fix: show profile picture in share sheet

---

mastodon/src/main/java/org/joinmastodon/android/fragments/HashtagTimelineFragment.java

Fixes an issue, where the tooltip for muting a hashtag would show the stringified version, instead of the hashtag name.

fix(HashtagTimeline): show hashtag name in mute icon tooltip

---

mastodon/src/main/java/org/joinmastodon/android/model/AltTextFilter.java
mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/StatusDisplayItem.java
mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/WarningFilteredStatusDisplayItem.java
mastodon/src/main/java/org/joinmastodon/android/ui/utils/InsetStatusItemDecoration.java
mastodon/src/main/res/layout/display_item_warning.xml

Applies the inset to the `WarningFilteredStatusDisplayItem`, allowing it to display the inset for quotes, making it easier to distinguish between the actual status and the filtered quote.
| Before                                                                                                                             	| After                                                                                                                                	|
|------------------------------------------------------------------------------------------------------------------------------------	|--------------------------------------------------------------------------------------------------------------------------------------	|
| ![WarningFilteredStatusDisplayItem without …

feat: apply inset to filter warning

---

mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/StatusDisplayItem.java

Fixes an issue where unofficial quotes from servers with a long TLD would not render as quotes.
Also changes it so quotes are only shown for status without additional attachments, as it can be quite overwhelming and visually displeasing otherwise.

fix: correctly render more unofficial quotes

---

mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsAboutAppFragment.java
mastodon/src/main/java/org/joinmastodon/android/utils/Tracking.java

Fixes a regression in 34f3e33efc06ec4ebf91a5ba02feccc82dc69bbb, which caused to copy crash log setting to crash. It can be mitigated by checking if the given URI is hierarchical, as otherwise the `getQueryParameterNames` function will throw an exception.

fix: check if uri is hierarchical

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ScheduledStatusListFragment.java
mastodon/src/main/java/org/joinmastodon/android/model/ScheduledStatus.java

Updates the ScheduledStatusList to (somewhat) correctly highlight and format the ScheduledStatus by injecting the correct HTML tags.
Closes https://github.com/LucasGGamerM/moshidon/issues/478.

feat(Draft): display ScheduledStatus highlighted and formatted

---

mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverFragment.java

Fixes a regression in 5edbe9b82666e17c0f103678da6209ef7e9eaf17, whcih did not switch the fragments everywhere. This caused the scroll-to-top functionality to not work and the posts to not immediatly load.
Closes https://github.com/LucasGGamerM/moshidon/issues/483.

fix(Discover): switch post and hashtag fragments everywhere

---

mastodon/src/main/java/org/joinmastodon/android/fragments/BaseStatusListFragment.java
mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/StatusDisplayItem.java

Updates the non-official quotes to completely hide the post of the account of the quote is muted or blocked. This is consistent with other platform with native quotes like Misskey, as well as Mastodon mutes/blocks.
Closes https://github.com/LucasGGamerM/moshidon/issues/488

feat(Quote): hide quotes of accounts that are muted/blocked or filtered.

---

mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverTrendingLinkTimelineFragment.java
mastodon/src/main/res/drawable/ic_fluent_document_one_page_24_filled.xml
mastodon/src/main/res/menu/trending_links_timeline.xml

Updates the TrendingLink Timeline to display the correct URL (now that the web version has a UI) and updates the icon of the Read action. The previous icon made it hard to recognize what the action was supposed to do. Additionally, the new one also indicates that it will take the user to an external website.

feat(Timeline/TrendingLinks): display URL, update icon

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ProfileFragment.java
mastodon/src/main/res/values/strings_mo.xml

It can be quite unclear if the note has been saved. This adds a toast, to indicate that the profile note has been saved.
On a sidenote, saving currently does not work when pressing the back button, though this should be solved when merging upstream.

feat(Profile): display Toast when saving note

---

mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/StatusDisplayItem.java

This fixes crashes in the ScheduledStatusListFragment, as ScheduledStatus do not contain an account (nor are they able to display quotes, but this catches both).

fix(StatusDisplayItem): check if account is null before adding quote

---

mastodon/src/main/java/org/joinmastodon/android/ExternalShareActivity.java

Fixes https://github.com/sk22/megalodon/issues/926.

fix(ExternalShareActivity): set theme before opening compose

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ProfileFragment.java

Fixes an issue, where the context used for displaying the note saved toast could sometimes be null on actual device. I did not encounter this on the emulator. My best guess is that, since currently, the note is only saved once actually exiting the fragment, and not on back pressing, the fragment context has already been cleaned up.

fix(Profile) note save crash

---

mastodon/src/main/java/org/joinmastodon/android/ui/sheets/MuteAccountConfirmationSheet.java

Partially reverts https://github.com/LucasGGamerM/moshidon/commit/6c519b3cb9d036e3da43e7bb0a6b86f81e5c9dff to use the full row again, but keeps the selection in a dialog. This improves the UI, as the secondary button is confusing, and feels out-of-place.
Also fixes an issue, where the selected duration would not be updated when re-opening the dialog.

feat(MuteSheet): revert to row

---

FAQ.md
README.md

Cleaned up the formatting and content of the README page so it's easier to parse for potential new users. The focus was on highlighting features other mastodon apps don't have and all the customization options while keeping it succinct and clean. 
Still needs some screenshots inserted which are described in [ placeholder boxes ] - I was hoping Lucas could take them with the official moshidon account, if you drop them in a folder I can do any cropping/editing and putting the links into the actual readme before merging.
I also moved the list that used to be in the readme of detailed changes with the links to specific issues/pull requests into the FAQ in case you wanted to keep that part for your own reference. 
It's been a while since I've done a github PR so feedback / corrections are …

Updated README formatting & content

---

mastodon/src/main/java/org/joinmastodon/android/fragments/HashtagTimelineFragment.java

Fixes an issue, where the menu follow icon was not correctly updated, and would always show the follow state.

fix(HashtagTimeline): update follow menu icon

---

mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/ErrorStatusDisplayItem.java
mastodon/src/main/java/org/joinmastodon/android/ui/text/HtmlParser.java

Disables clicking the ErrorStatusDisplayItem, since there is no valid content to be displayed.
Also fixes an issue, where non-mastodon posts could have hashtags without any text, which could lead to an oob String access, e.g.:
https://mastodon.social/@info@hamishcampbell.com/113050670800313268

feat(Error): disable clicking + crash fix

---

mastodon/src/main/java/org/joinmastodon/android/fragments/HashtagTimelineFragment.java

Fixes a crash when clicking on hashtags in profiles, since the hashtag is for some reason null.

fix(Timeline/Hashtag): check if hashtag is null

---

build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
settings.gradle

- Upgrade to Gradle 8.11
- Upgrade to Android Gradle Plugin 8.7.2
- Remove deprecated android.defaults.buildfeatures.buildconfig=true gradle property, it is not needed as mastodon/build.gradle already sets android { buildFeatures { buildConfig true } }
- Move plugin repository definition to settings.gradle to match latest Gradle practices
- Move to using plugin {} mechanism to add Android Gradle Plugin to match the latest Gradle practices
- Remove root project clean task as this project does not produce any real artifacts, it seems to be leftover from original Android new project template

Upgrade build dependencies for the project

---

mastodon/src/main/java/org/joinmastodon/android/api/requests/statuses/AkkomaTranslateStatus.java

Not sure if something has changed in the Akkoma API since the latest version of `AkkomaTranslateStatus`, but it seems that the API expects the target language to be _lowercase_ (not _uppercase_).
Libretranslate nginx traces from my instance with the current implementation show a 400 with the current implementation:
```
1.2.3.4 - - [11/Feb/2025:11:40:34 +0100] "POST /translate HTTP/1.1" 400 32 "-" "Akkoma 3.13.2-0-g050bc74; https://myinstance.social <fabio@myinstance.social>"
```
And that's also mirrored on my Akkoma logs:
```
1.2.3.4 - - [11/Feb/2025:11:40:35 +0100] "GET /api/v1/statuses/Ar0PZaoyJwN2GD3UJs/translations/EN HTTP/2.0" 400 54 "-" "MoshidonAndroid/2.3.0+fork.108.moshinda"
```
A direct API call to the endpoint above indeed returns a 400:
```
{"error":"libre_translate: request …
```

[#346] Fix Akkoma translations.

---

mastodon/build.gradle
mastodon/src/main/java/org/joinmastodon/android/MastodonApp.java
mastodon/src/main/java/org/joinmastodon/android/PushNotificationReceiver.java
mastodon/src/main/java/org/joinmastodon/android/UnifiedPushNotificationReceiver.java
mastodon/src/main/java/org/joinmastodon/android/api/PushSubscriptionManager.java
mastodon/src/main/java/org/joinmastodon/android/api/requests/notifications/RegisterForPushNotifications.java
mastodon/src/main/java/org/joinmastodon/android/api/session/AccountSessionManager.java
mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsNotificationsFragment.java
mastodon/src/main/java/org/joinmastodon/android/utils/UnifiedPushHelper.java
settings.gradle

- UnifiedPush lib version 3.0.0 and above can automatically handle webpush decryption
- Mastodon version 4.4.0 and above [will support standard webpush encryption](https://github.com/mastodon/mastodon/pull/33528)
This PR takes advantage of the 2 previous news to used the content of (decrypted) push notifications with UnifiedPush when it is possible.
For the moment, legacy encryption is still used with FCM, but it is possible to migrate to the standard for FCM too. I will link the PR to the webpush->FCM bridge used when opened.
I've also added another change (on MastodonApp.java). It may have been better to use another PR but this is pretty small change, so I hope it's OK: when opening the application, if the users uses UnifiedPush, we don't register to FCM and we register to UnifiedPush …

Standard push + UnifiedPush update

---

mastodon/src/main/java/org/joinmastodon/android/fragments/HashtagTimelineFragment.java
mastodon/src/main/java/org/joinmastodon/android/ui/sheets/AccountRestrictionConfirmationSheet.java
mastodon/src/main/java/org/joinmastodon/android/ui/sheets/MuteAccountConfirmationSheet.java
mastodon/src/main/java/org/joinmastodon/android/ui/sheets/MuteHashtagConfirmationSheet.java
mastodon/src/main/res/values/strings_mo.xml

Shows a MuteHashtagConfirmationSheet when muting a hashtag, similar to the MuteAccountConfirmationSheet. The sheet contains a new duration option, which will let the mute expire after the chosen duration.
Also adds a snackbar for when a hashtag is successfully unmuted.

feat(Timeline/Hashtag): show confirmation sheet when muting

---

mastodon/src/main/java/org/joinmastodon/android/fragments/NotificationsListFragment.java

- Some notifications will have the status attribute set as null and the if in 128 is trying to access to attributes from a null object, causing a NPE as soon as the app is opened.

Fix a NullPointerException in NotificationsListFragment.java
